export const DAO_ABI = [
  "constructor(address _token, uint256 _quorumPercent)",
  "event ProposalCancelled(uint256 indexed id)",
  "event ProposalCreated(uint256 indexed id, address indexed creator, address target, uint256 snapshotId, uint256 deadline)",
  "event ProposalExecuted(uint256 indexed id)",
  "event VoteCast(uint256 indexed id, address indexed voter, bool support, uint256 weight)",
  "function ADMIN_ROLE() view returns (bytes32)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function cancelProposal(uint256 proposalId)",
  "function createProposal(address target, bytes data, uint256 deadline) returns (uint256)",
  "function executeProposal(uint256 proposalId)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function grantRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function hasVoted(uint256, address) view returns (bool)",
  "function proposals(uint256) view returns (address target, bytes data, uint256 snapshotId, uint256 deadline, uint256 forVotes, uint256 againstVotes, bool executed, address creator)",
  "function quorumPercent() view returns (uint256)",
  "function renounceRole(bytes32 role, address account)",
  "function revokeRole(bytes32 role, address account)",
  "function setQuorumPercent(uint256 _q)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function token() view returns (address)",
  "function vote(uint256 proposalId, bool support)",
];

export const TOKEN_ABI = [
  "constructor(string name, string symbol, uint256 initialSupply)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)",
  "event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)",
  "event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)",
  "event Snapshot(uint256 id)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function SNAPSHOT_ROLE() view returns (bytes32)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function balanceOf(address account) view returns (uint256)",
  "function balanceOfAt(address account, uint256 snapshotId) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function decreaseAllowance(address spender, uint256 subtractedValue) returns (bool)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function grantRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function increaseAllowance(address spender, uint256 addedValue) returns (bool)",
  "function name() view returns (string)",
  "function renounceRole(bytes32 role, address account)",
  "function revokeRole(bytes32 role, address account)",
  "function snapshot() returns (uint256)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function totalSupplyAt(uint256 snapshotId) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
];

export const MOCK_TARGET_ABI = [
  "function setValue(uint256 v)",
  "function value() view returns (uint256)",
];
